include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**
    - test/**
    - plugins/**

linter:
  rules:
    prefer_single_quotes: true
    sort_constructors_first: true
    empty_constructor_bodies: true
    sort_child_properties_last: true
    unnecessary_lambdas: true
    avoid_void_async: true
    unawaited_futures: true
    discarded_futures: true # new 2.18 lint, should be used in conjunction with unawaited_futures
    prefer_relative_imports: true
    prefer_interpolation_to_compose_strings: true
    join_return_with_assignment: true
    use_build_context_synchronously: true
    omit_local_variable_types: false         # too strict; warns even about primitive int/bool types
    prefer_const_constructors: false         # causes too much warnings
    lines_longer_than_80_chars: false        # we use 120 chars by internal convention
    use_key_in_widget_constructors: false    # key is not necessary in most cases